### ISSUE TITLE
Avoiding over-crabbing is maybe not needed ?

### ISSUE THREAD

**Issue by freddieknets** [lhcopt/lhcmask#13]
In module_01:
!Avoid crabbing more than the crossing angle
if ( abs(on_crab1)>abs(on_x1) && on_crab1 <> 0) {on_crab1 = abs(on_crab1)/on_crab1 * abs(on_x1);}
if ( abs(on_crab5)>abs(on_x5) && on_crab5 <> 0) {on_crab5 = abs(on_crab5)/on_crab5 * abs(on_x5);}

I discussed with Gianni, and we believe that this limiting is unneeded. The user sets both the crabbing angle and the crossing angle, so he's aware what he's doing (he might even want to simulate over-crabbing on purpose, following the idea that he doesn't know the value of the crossing angle very well).

As an alternative, we might output a warning when over-crabbing.

**Comment by giadarol** [comment]
This check was already removed since a while
