### ISSUE TITLE
XMA and YMA in the BB lenses generated by python (only in MADX)

### ISSUE THREAD

**Issue by sterbini** [lhcopt/lhcmask#37]
Hi, 
there seems to be a bug if one uses the BB lenses installed in MADX the the python BB modules
NOTA BENE
- no effect on SixTrack input which is correct (GOOD)
- BUT if you compute footprints/tracking in MADX with BB there is an issue (BAD).

The incriminated line is 
https://github.com/lhcopt/lhcmask/blob/8505216d790a2c9957184cc126dadeffc12e3e3b/pymask/beambeam.py#L273

The point is that XMA/YMA is wrongly referred to the weak beam orbit instead of to the reference orbit (aka ideal orbit in the MAD-X manual). 
Investigations are on going for the fix:
- [x] check with the new python BB functions that the separations are the same in MAD lenses and SixTrack input (wrongly).
- [x] check with legacy BB macros the  XMA/YMA are "half"  of the SixTrack separations (correctly).

**Comment by sterbini** [comment]
As a complement to the previous issue, one can see the problem by comparing the XMA and YMA with legacy python macros 
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/25726245/110609995-19048d80-818e-11eb-903f-ca8e314733ff.png">

**Comment by sterbini** [comment]
As a complement, the fc.3 files are not impacted by the bug
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/25726245/110615644-ee1d3800-8193-11eb-923a-6c808a437da4.png">

**Comment by sterbini** [comment]
After checks, we propose the https://github.com/sterbini/lhcmask/commit/78af1e2c02097a566c72e4594d0c0947a97f0b66 fix. 
We confirm that the fix will have not effect of the fc.* files produced by MDX-X (as expected) but the fc.34 that is not used in SixTrack.

**Comment by giadarol** [comment]
Cool. I guess we for Pull Request -> Merge -> Release?

**Comment by sterbini** [comment]
The pull request for the fix was merged and deployed on afs.
