### ISSUE TITLE
Error calling tracker.compute_one_turn_matrix_finite_differences()

### ISSUE THREAD

**Issue by pbelange** [lhcopt/lhcmask#69]
Error running 000_pymask.py returning the following:
```python
File ~/Apps/lhcmask/pymask/pymasktools.py:456, in generate_xsuite_line(mad, seq_name, bb_df, optics_and_co_at_start_ring_from_madx, folder_name, skip_mad_use, prepare_line_for_xtrack, steps_for_finite_diffs)
    452 xf.configure_orbit_dependent_parameters_for_bb(tracker,
    453                    particle_on_co=particle_on_tracker_co)
    455 _disable_beam_beam(tracker.line)
--> 456 RR_finite_diffs = tracker.compute_one_turn_matrix_finite_differences(
    457         particle_on_tracker_co,
    458         **steps_for_finite_diffs)
    459 _restore_beam_beam(tracker.line)
    462 (WW_finite_diffs, WWInv_finite_diffs, RotMat_finite_diffs
    463         ) = xp.compute_linear_normal_form(RR_finite_diffs)

TypeError: compute_one_turn_matrix_finite_differences() got an unexpected keyword argument 'dx'
```

The error is tracked down to 
https://github.com/lhcopt/lhcmask/blob/b4b6d2a395f18c356df90918f462cb6371e9f021/pymask/pymasktools.py#L456-L458

where `**steps_for_finite_diffs` should be replaced by `steps_for_finite_diffs`, i.e. the function expects a dictionary, not an unpacked version of it. See :
https://github.com/xsuite/xtrack/blob/b090594d7564fec044361aeee29a661308ea6803/xtrack/twiss_from_tracker.py#L54-L68

**Comment by giadarol** [comment]
@pbelange Thanks for riporting this, will be addressed with high priority

**Comment by giadarol** [comment]
The problem should be solved now. Please download the latest version of xtrack (v0.6.1) and the latest version of lhcmask (v1.2.1).

@pbelange Don't hesitate to reopen the issue in case you still see problems.
