### ISSUE TITLE
MADX versions

### ISSUE THREAD

**Issue by sterbini** [lhcopt/lhcmask#8]
Hi,

making tests of the examples (examples/hl_lhc_collision) I ran it
1. from my machine NUCBE16940 with  MAD-X 5.05.02  (64 bit, Linux) **compiled locally** 
2. from my machine NUCBE16940 with  MAD-X 5.05.02  (64 bit, Linux) **obtained from lxplus at /afs/cern.ch/user/m/mad/bin/madx** 
3. from lxplus with  MAD-X 5.05.02  (64 bit, Linux) **obtained from lxplus at /afs/cern.ch/user/m/mad/bin/madx**

All the 3 outputs are different (by "small" but "unexpected" amount). And btw are **significant** different from the output of the repository in /afs/cern.ch/eng/lhc/optics/simulation_tools/modules/examples/hl_lhc_collision/
(obtain  from Gianni's machine using the  /afs/cern.ch/user/m/mad/bin/mad **but** one need to verify for which version was obtained (probably non the last one).

So I suggest clarifying the numerical dependence of the MAD-X results on the platform. 

Cheers,
G.

**Comment by sterbini** [comment]
We checked with Gianni. Working with MAD-X 5.05.02 the results is the same between Point 3 (see above) and Gianni's machine running MAD-X from afs.
Difference persists when I recompiled MAD-X (see meld below)
![image](https://user-images.githubusercontent.com/25726245/75656679-be744f80-5c64-11ea-8d6b-8cdf5b8b6f82.png).
I will check with @rdemaria

**Comment by rdemaria** [comment]
Difference persists with the same version but different compilation?

**Comment by sterbini** [comment]
Yes. I am not sure if I used the correct version of the compiler. I will check and let you know.

**Comment by sterbini** [comment]
Here you are my version of the compilers.
```
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

GNU Fortran (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

cmake version 3.10.2
```

I got this differences wrt the lxplus MAD-X version (in both cases  5.05.02).

![image](https://user-images.githubusercontent.com/25726245/75771537-76c7f380-5d4a-11ea-90d0-32a58f9bd796.png)

After discussing with @rdemaria and @giadarol, it is most likely related to a different compiler version.
in fact on lxplus we have
```
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- The Fortran compiler identification is GNU 8.3.0
```
G.
